
version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: task-manager-api
    restart: unless-stopped
    ports:
      - "5000:80"
    environment:
      - APP_ENV=development
      - DB_HOST=mysql_db
      - DB_USER=root
      - DB_PASSWORD=your_mysql_password
      - DB_NAME=task_manager
    volumes:
      - ./api:/var/www/html
    depends_on:
      - mysql_db
    networks:
      - app-network

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
